sudo: required
before install:
  sudo apt-get install -y libeigen3-dev nlohmann-json-dev

language: cpp
dist: bionic

compiler:
  - gcc
  - clang
addons:
  apt:
    update: true

script:
  - make build run