sudo: required
language: cpp
dist: bionic

before_install:
  - sudo apt-get install -y libeigen3-dev nlohmann-json-dev
  - pip install --user pyyaml cpp-coveralls

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - gcovr
      - lcov
    update: true

script:
  - cmake --version
  - make clean build
  - ./build/bin/unit-tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'