sudo: required
language: cpp
dist: bionic

before_install:
  - sudo apt-get install -y libeigen3-dev nlohmann-json-dev
  - pip install --user pyyaml cpp-coveralls



compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - lcov
      - gcovr
    update: true

script:
  - cmake --version
  - make build run

after_success:
  coveralls -i gfm2d