sudo: required
before install:
  sudo apt-get install -y libeigen3-dev

language: cpp
dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true

script:
  - cmake --version
  - ls /usr/share
  - make build run