sudo: required
language: cpp
dist: bionic

before_install:
  - sudo apt-get install -y libeigen3-dev nlohmann-json-dev
  - pip install --user pyyaml cpp-coveralls

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - gcovr
      - lcov
    update: true

script:
  - cmake --version
  - make clean build
  - ./build/bin/unit-tests

after_success:
after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info coverage info
  - lcov --remove coverage.info '*/usr/*' --output-file coverage.info 
  - lcov --remove coverage.info '*/inc/*' --output-file coverage.info 
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'